/*
 * Swagger Hello World
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SwaggerHelloWorld);
  }
}(this, function(expect, SwaggerHelloWorld) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SwaggerHelloWorld.GreetApi();
  });

  describe('(package)', function() {
    describe('GreetApi', function() {
      describe('greet', function() {
        it('should call greet successfully', function(done) {
          // TODO: uncomment greet call and complete the assertions
          /*

          instance.greet(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a('string');
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('greetUser', function() {
        it('should call greetUser successfully', function(done) {
          // TODO: uncomment, update parameter values for greetUser call and complete the assertions
          /*
          var body = new SwaggerHelloWorld.User();
          body.firstName = "";
          body.lastName = "";
          body.email = "";

          instance.greetUser(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a('string');
            // expect(data).to.be(null);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
