/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.15).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2020-10-01T12:54:49.392Z")

@Api(value = "greet", description = "the greet API")
@RequestMapping(value = "/v1")
public interface GreetApi {

    @ApiOperation(value = "Say hello world!", nickname = "greet", notes = "You can use this witout a user.", response = String.class, tags={ "greet", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Will respond Hello World!", response = String.class) })
    @RequestMapping(value = "/greet",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<String> greet();

}
